version: '3.7'
services:
  server:
    container_name: ui-admin-server
    build:
      context: ./server/
    command: /app/node_modules/.bin/nodemon src/index.js
    env_file:
      - /server/env/test.env
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    networks:
      - tools_proxy   
  client:
    container_name: ui-admin-client
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - tools_proxy   
    ports:
      - "8080:3000"
networks:
  tools_proxy:
      name: tools_network
      external: true
