version: '3.7'
services:
  server:
    build:
      context: ./server/
    command: /app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - tools_proxy   
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - tools_proxy   
    ports:
      - "8080:3000"
networks:
  tools_proxy:
    external:
      name: tools_network