apiVersion: v1
kind: Service
metadata:
  name: service-ui-admin-v2
  namespace: hub
  labels:
    name: service-ui-admin-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: ui-admin-v2