apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-admin-v2
  namespace: hub
  labels:
    app: ui-admin-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-admin-v2
  template:
    metadata:
      labels:
        app: ui-admin-v2
    spec:
      containers:
      - name: ui-admin-v2
        image: image_to_be_replaced
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: ui-admin-v2-conf
        resources:
          limits:
            memory: "1000Mi"
          requests:
            memory: "1000Mi"
